spring.application.name=auth
app.web.path-prefix=auth
server.port=8082
jwt.secret=supergeheimeschluesselfuerjwttoken12345
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
